//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Uzytkownicy
    {
        public int ID { get; set; }
        public string LOGIN { get; set; }
        public string PASSWORD { get; set; }
        public string IMIE { get; set; }
        public string NAZWISKO { get; set; }
        public int IdRola { get; set; }
    }
}
